# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swish}
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Weiskotten"]
  s.date = %q{2011-03-06}
  s.description = %q{A Ruby wrapper for the Dribbble API}
  s.email = %q{jeremy@weiskotten.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/dribbble/base.rb",
    "lib/dribbble/comment.rb",
    "lib/dribbble/paginated_list.rb",
    "lib/dribbble/player.rb",
    "lib/dribbble/shot.rb",
    "lib/swish.rb",
    "swish.gemspec",
    "test/base_test.rb",
    "test/comment_test.rb",
    "test/helper.rb",
    "test/paginated_list_test.rb",
    "test/player_test.rb",
    "test/shot_test.rb"
  ]
  s.homepage = %q{http://github.com/jeremyw/swish}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby wrapper for the Dribbble API}
  s.test_files = [
    "test/base_test.rb",
    "test/comment_test.rb",
    "test/helper.rb",
    "test/paginated_list_test.rb",
    "test/player_test.rb",
    "test/shot_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<crack>, [">= 0.1.8"])
      s.add_development_dependency(%q<httparty>, [">= 0.6.1"])
    else
      s.add_dependency(%q<crack>, [">= 0.1.8"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
    end
  else
    s.add_dependency(%q<crack>, [">= 0.1.8"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
  end
end

